In [6]:
import luigi
import subprocess
from datetime import datetime
import os

In [ ]:
class RunFutureKlinesScript(luigi.Task):
    def output(self):
        return luigi.LocalTarget('/home/nas/user_data/suncong/binance_data/logs/future_klines_log_'+datetime.now().strftime('%Y%m%d')+'.txt')

    def run(self):
        with open(self.output().path, 'w') as out_file:
            subprocess.run(['/bin/bash', '/path/to/daily_update_future_klines.sh'], stdout=out_file, stderr=subprocess.STDOUT)

class RunSpotKlinesScript(luigi.Task):
    def output(self):
        return luigi.LocalTarget('/home/nas/user_data/suncong/binance_data/logs/spot_klines_log_'+datetime.now().strftime('%Y%m%d')+'.txt')

    def run(self):
        with open(self.output().path, 'w') as out_file:
            subprocess.run(['/bin/bash', '/path/to/daily_update_spot_klines.sh'], stdout=out_file, stderr=subprocess.STDOUT)

class RunAllScripts(luigi.WrapperTask):
    def requires(self):
        return [RunFutureKlinesScript(), RunSpotKlinesScript()]

In [7]:
class RunAutoUpdateDaily(luigi.Task):
    """
    A Luigi Task that runs the auto_update_daily script.
    """

    def output(self):
        # Specify a file to indicate the task completion status
        return luigi.LocalTarget('/home/nas/user_data/suncong/binance_data/logs/auto_update_log_'+datetime.now().strftime('%Y%m%d')+'.txt')

    def run(self):
        # Run the shell script using subprocess
        script_path = "/home/suncong/work/trading/binance-public-data/shell/auto_update_daily.sh"
        
        with open(self.output().path, 'w') as out_file:
            subprocess.run([script_path], stdout=out_file, stderr=subprocess.STDOUT)

In [8]:
import pandas as pd

In [13]:
df = pd.read_csv('/home/nas/user_data/suncong/binance_data/klines_1m/um/BTCUSDT/BTCUSDT-1m-2024-08.csv')

In [10]:
df

,open_time,open,high,low,close,volume,close_time,quote_volume,count,taker_buy_volume,taker_buy_quote_volume,ignore
0,1722470400000,64601.8,64653.2,64577.0,64612.6,547.687,1722470459999,3.538584e+07,5407,321.950,2.080084e+07,0
1,1722470460000,64612.7,64663.3,64600.1,64648.0,276.696,1722470519999,1.788621e+07,3002,199.501,1.289608e+07,0
2,1722470520000,64647.9,64682.7,64600.9,64600.9,165.142,1722470579999,1.067461e+07,2215,88.023,5.689906e+06,0
3,1722470580000,64601.0,64675.4,64600.9,64666.0,130.380,1722470639999,8.427176e+06,2102,74.602,4.822204e+06,0
4,1722470640000,64666.0,64689.8,64655.1,64655.9,81.719,1722470699999,5.284775e+06,1475,44.387,2.870573e+06,0
...,...,...,...,...,...,...,...,...,...,...,...,...
44635,1725148500000,58952.9,58953.0,58952.9,58952.9,10.289,1725148559999,6.065669e+05,194,5.068,2.987738e+05,0
44636,1725148560000,58952.9,58953.0,58941.9,58942.0,13.918,1725148619999,8.204896e+05,398,5.570,3.283577e+05,0
44637,1725148620000,58941.9,58944.4,58941.9,58941.9,10.181,1725148679999,6.000894e+05,234,7.001,4.126535e+05,0
44638,1725148680000,58941.9,58942.0,58941.8,58941.8,5.967,1725148739999,3.517063e+05,163,2.265,1.335035e+05,0
44639,1725148740000,58941.9,58946.4,58941.8,58941.9,9.822,1725148799999,5.789600e+05,240,4.865,2.867651e+05,0

In [14]:
pd.to_datetime(df['open_time'], unit='ms')

0       2024-08-01 00:00:00
1       2024-08-01 00:01:00
2       2024-08-01 00:02:00
3       2024-08-01 00:03:00
4       2024-08-01 00:04:00
                ...
44635   2024-08-31 23:55:00
44636   2024-08-31 23:56:00
44637   2024-08-31 23:57:00
44638   2024-08-31 23:58:00
44639   2024-08-31 23:59:00
Name: open_time, Length: 44640, dtype: datetime64[ns]